"""add topics

Revision ID: 4344458de545
Revises: 63c40dc78d4c
Create Date: 2017-10-25 15:20:33.724883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4344458de545'
down_revision = '63c40dc78d4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('topics', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'topics')
    # ### end Alembic commands ###
